### ISSUE TITLE
Timezone keeps updating on Debian

### ISSUE THREAD

**Issue by sbakker** [saz/puppet-timezone#22]
When applying the timezone class on my Debian 7 system, every agent run will result in a refresh of `/etc/timezone`. What happens is:

`/etc/timezone` contains:
````
Europe/Amsterdam
````

Agent runs, replaces the content with:
````
# Managed by puppet - do not modify
Europe/Amsterdam
````

Agent runs `dpkg-reconfigure -f noninteractive tzdata`, which *rewrites* `/etc/timezone`:
````
Europe/Amsterdam
````

This repeats itself every time the manifest is applied.

Not sure how this is handled on other systems, but for Debian the file (and thus the template) should not contain anything other than the time zone string.

For now, I've worked around this by doing:
````
$zone = hiera('timezone')
if $zone != $::timezone {
   class { timezone: timezone => $zone }
}
````

**Comment by anthonysomerset** [comment]
I'm seeing this also in Ubuntu 14.04LTS

**Comment by craigwatson** [comment]
Confirmed that this is also affecting Ubuntu 14.04 LTS for me too :(

**Comment by t0xicCode** [comment]
Both #21 and #23 deal with this issue.

**Comment by t0xicCode** [comment]
In the meantime, v3.1.1 doesn't include the comment in the template.

**Comment by saz** [comment]
This is fixed in the current master and in the next release.
