### ISSUE TITLE
Unknown function validate_bool 

### ISSUE THREAD

**Issue by dipposh** [saz/puppet-timezone#25]
Perhaps I've missed some dependency as I'm quite new to Puppet.  But in Geppetto it there is an error on line 56 of init.pp which says "Unknown function validate_bool".  I also see this error when I try and apply the module.

**Comment by Kriechi** [comment]
Include the following puppet modules: stdlib (and maybe concat)

**Comment by saz** [comment]
puppetlabs/stdlib is a dependency of this module, which seems to be missing on your system.
