### ISSUE TITLE
Unable to install with librarian-puppet

### ISSUE THREAD

**Issue by gergnz** [saz/puppet-timezone#26]
It seems that the metadata.json somehow upsets librarian puppet.  I have forked deleted it, and installed using librarian puppet.

If I use librarian puppet I get:
/etc/puppet/vendor/ruby/1.9.1/gems/her-0.7.4/lib/her/model/attributes.rb:192: stack level too deep (SystemStackError)

Which looks like it doesn't like the name "saz-timezone". If I change the name to "saz-tzone" it works.

OS: Ubuntu 14.04.2
Standard ruby.
New install.

**Comment by saz** [comment]
This is no issue with my module, as it has been working with librarian-puppet.
If this problem still exists in the newest librarian-puppet release, please open an issue on librarian-puppet.

Thanks!
