### ISSUE TITLE
hwutc should be a string, but docs do not specify, and puppet returns error.

### ISSUE THREAD

**Issue by felipe1982** [saz/puppet-timezone#29]
`hwutc => true,` causes an error but `hwutc => 'true',` Just Works. This should be reflected in the documentation, or the code can somehow translate boolean to string (?!).

**Comment by ptierno** [comment]
or just change `<% if !@hwutc.empty? -%>` to `<% if @hwutc %>` in the template.
and maybe add a `validate_bool($hwutc)` in `init.pp`
@saz would you like a PR for this?

**Comment by felipe1982** [comment]
puppet-lint is _correcting_ this to a Boolean, and it causes this module to no longer work as required.
