### ISSUE TITLE
Can this module take params from an ENC?

### ISSUE THREAD

**Issue by salderma** [saz/puppet-timezone#31]
Hi,
I'm using Foreman as a Puppet ENC, Foreman has capabilities to apply parameters dynamically based on metadata like location, domain, or logical node groups.  Anyway, it seems as though this module won't take the timezone param from the ENC.

Location A sets the timezone param to America/New_York, Location B sets it to America/Los_Angeles.  Nodes in Location A have yaml like
```
classes:
  timezone
parameters:
  timezone_timezone: America/New_York
environment: production
```
The timezone always takes the default UTC param.  If I set it manually on a host with timedatectl, puppet sets it back to UTC.

Do you have any ideas?

**Comment by t0xicCode** [comment]
Are you sure that your foreman is configured correctly? I have my foreman set to distribute America/Toronto to my hosts, and the class picks them up just fine. The class itself doesn't even care or know where the values are coming from.

**Comment by saz** [comment]
@t0xicCode is right. This module takes params from an ENC such as foreman as any other module should do.
