### ISSUE TITLE
Out-of-the box  I got validate_bool unknown

### ISSUE THREAD

**Issue by astondevops** [saz/puppet-timezone#42]
I've done a git clone in my puppet modules directory and run it so I got an unknown validate_bool  error 
Thanks for your help 
Herve

**Comment by Devatoria** [comment]
Are you using Puppet 4 parser? This module is not yet compatible with it.

**Comment by saz** [comment]
I'm using this module with my puppet 4 installation. Can you be a little more specific? 


Sent using Boxer

**Comment by saz** [comment]
@astondevops can you paste the output of a run and the usage of this module in your infrastructure please? 


Sent using Boxer

**Comment by Devatoria** [comment]
My bad, this wasn't what I thought. This module **should not be compatible** with puppet 4 parser because it uses stdlib validate_bool function which will be deprecated soon in order to use puppet 4 typing system. Maybe I'll do a PR soon to use validate_legacy instead.

**Comment by saz** [comment]
@Devatoria Do you have any issues with this module and can paste some errors in here? Those methods are only deprecated and will be dropped in a future release, but they're still there.
@astondevops Can you paste the errors you're seeing? This will make it easier for me to help you.

**Comment by Devatoria** [comment]
I had but I fixed. It seems that it was inherent to my Puppet install and I thought it was related, but I was wrong. Sorry :)

**Comment by saz** [comment]
Then let's see, what @astondevops is saying :)

**Comment by saz** [comment]
As there is no response, I'll close this issue. Feel free to open a new one.
