### ISSUE TITLE
Accidental break in `master`?

### ISSUE THREAD

**Issue by mdwheele** [saz/puppet-timezone#52]
In https://github.com/saz/puppet-timezone/pull/37, a new dependency was added (`stm-debconf`) to replace a few `exec` resources that were calling `debconf-get-selections`. This module ensures that necessary packages are installed. 

In https://github.com/saz/puppet-timezone/pull/48, it looks like the change from `exec` to `debconf` resources was (accidentally?) reverted, re-introducing the issues reported (and resolved) in https://github.com/saz/puppet-timezone/issues/28. I believe it's accidental because the project still "depends" (`metadata.json`) on `stm-debconf`.

Is this intentional? If so, could this be patched in `master`?

**Comment by johanfleury** [comment]
These changes introduced some errors on my side and I had to install `debconf-utils` in order to make Puppet run correctly:

```
Error: /Stage[main]/Timezone/Exec[update_debconf area]: Could not evaluate: Could not find command 'debconf-get-selections'
Error: /Stage[main]/Timezone/Exec[update_debconf zone]: Could not evaluate: Could not find command 'debconf-get-selections'
```

**Comment by saz** [comment]
Should be fixed in the current master
