### ISSUE TITLE
Timezones with links are broken on ubuntu 16.04

### ISSUE THREAD

**Issue by spikebike** [saz/puppet-timezone#55]
If I try:
```
  class { timezone:
    timezone => 'America/Los_Angeles',
  }
```

When run puppet says this:
```
Notice: /Stage[main]/Timezone/File[/etc/localtime]/target: target changed '/usr/share/zoneinfo/America/Los_Angeles' to '../US/Pacific'
```

So the result is:
```
$ ls -al /etc/localtime 
lrwxrwxrwx 1 root root 13 Nov 29 05:22 /etc/localtime -> ../US/Pacific
```

But /etc/localtime using a relative link of ../US/Pacific results in /US/Pacific which doesn't exist there, but instead in /usr/share/zoneinfo.

However this works (it's not a link):
```
class { timezone:
    timezone => 'US/Pacific'
}
```

The problem is the timezone breaks if the /usr/share/timezone file is a link.  In particular America/Los_Angeles is a link to ../US/Pacific.  But the timezone is a relative link and it doesn't work from /etc.

This is on ubuntu-16.04.

**Comment by hansmi** [comment]
The same issue occurs with the timezone `Europe/Zurich` on Debian 9 (Stretch). `/etc/localtime` is replaced with a symlink to `Busingen`.

**Comment by Izzette** [comment]
Having the same issue on Ubuntu 14.04.5 LTS (Trusty Tahr) with `America/Chicago`, I believe this is a regression as the issue only occurred after I updated this module from [v3.4.0](https://github.com/saz/puppet-timezone/tree/v3.4.0) to [master](https://github.com/saz/puppet-timezone/tree/master).

**Comment by Izzette** [comment]
After some back tracking, I determined that this regression was introduced in 871cbd97222c58e1856bb3f70cddbcf7eaa6cc49.
