### ISSUE TITLE
/etc/timezone is updated on every Puppet execute on Debian

### ISSUE THREAD

**Issue by juan-borla** [saz/puppet-timezone#58]
Every time the Puppet Agent is executed, the /etc/timezone file is updated.

Example of the output (note: the from and to are consistent between runs)
`Notice: /Stage[main]/Timezone/File[/etc/timezone]/content: content changed '{md5}4f24b133ba38d8fd565168742c9aedeb' to '{md5}ae1d80ba85332ae2d9fbbd491b17c043'
Info: /Stage[main]/Timezone/File[/etc/timezone]: Scheduling refresh of Exec[update_timezone]`

Module Version: 4.0.1
Puppet Version: 4.8.2
System: Debian 9.1 x64

**Comment by nferch** [comment]
Getting this as well on Ubuntu xenial.

Based on your hashes, I assume you're trying to set the timezone to UTC as well. Setting the timezone to `Etc/UTC` seems to be a workaround.

**Comment by saz** [comment]
Should be fixed in the current master

**Comment by nferch** [comment]
Still happening for me:

```
Notice: /Stage[main]/Timezone/Debconf[tzdata/Areas]/value: value changed 'Etc' to 'UTC'
Notice: /Stage[main]/Timezone/File[/etc/timezone]/content: 
--- /etc/timezone       2018-01-15 13:57:46.896132167 -0500
+++ /tmp/puppet-file20180115-19406-x2ylqc       2018-01-15 14:11:18.281672170 -0500
@@ -1 +1 @@
-Etc/UTC
+UTC

Info: Computing checksum on file /etc/timezone
Info: FileBucket got a duplicate file {md5}4f24b133ba38d8fd565168742c9aedeb
Info: /Stage[main]/Timezone/File[/etc/timezone]: Filebucketed /etc/timezone to puppet with sum 4f24b133ba38d8fd565168742c9aedeb
Notice: /Stage[main]/Timezone/File[/etc/timezone]/content: 

Notice: /Stage[main]/Timezone/File[/etc/timezone]/content: content changed '{md5}4f24b133ba38d8fd565168742c9aedeb' to '{md5}ae1d80ba
85332ae2d9fbbd491b17c043'
Info: /Stage[main]/Timezone/File[/etc/timezone]: Scheduling refresh of Exec[update_timezone]
Notice: /Stage[main]/Timezone/Exec[update_timezone]: Triggered 'refresh' from 1 events
```
