### ISSUE TITLE
Ubuntu error - debconf-get-selections

### ISSUE THREAD

**Issue by acurus-puppetmaster** [saz/puppet-timezone#63]
When puppet runs the following error is reported under Ubuntu 16.04
```
Error: /Stage[main]/Timezone/Exec[update_debconf area]: Could not evaluate: Could not find command 'debconf-get-selections'
Error: /Stage[main]/Timezone/Exec[update_debconf zone]: Could not evaluate: Could not find command 'debconf-get-selections'
```
This is because the package debconf-utils is not installed as a default in Ubuntu 16.04, this module requires it so really should install it to work.

**Comment by saz** [comment]
This issue should be fixed in master. A new version will be released soon.
