### ISSUE TITLE
In RHEL7/CentOS7, /etc/localtime is not a symbolic link to the corresponding file in /usr/share/zoneinfo

### ISSUE THREAD

**Issue by knoha-rh** [saz/puppet-timezone#71]
Hi maintainers,

In RHEL7/CentOS7, /etc/localtime is not a symbolic link to the corresponding file in /usr/share/zoneinfo.
The current implementation copies the file in /usr/share/zoneinfo to /etc/localtime.
It causes that timedatectl command cannot show the correct timezone information and /var/log/messages shows incorrect date information.

Best Regards,
Keigo Noha

**Comment by saz** [comment]
Is this happening with the newest release?

**Comment by tmannerm** [comment]
FWIW, for me /etc/localtime is a symlink correctly on both CentOS 6 and 7 with  v5.0.2 of the module. It was also a link when I was using v3.0.1 before.

**Comment by knoha-rh** [comment]
Hello team,

Thank you for your comments on this report. I confirmed that the latest release doesn't have this issue.
I need to confirm it before I opened this issue request. I really appreciate your suggestions on this ticket.

Now, I close this ticket.

Best Regards,
Keigo Noha
