### ISSUE TITLE
Notify service rsyslog on CentOS because time is not adjusted for logs?

### ISSUE THREAD

**Issue by siebrand** [saz/puppet-timezone#80]
I've noticed a few times that after changing the timezone, the log entries in /var/log/messages are not updated. When restarting rsyslog, the expected times are logged. Should service rsyslog be notified on CentOS after a time zone change?

**Comment by kenyon** [comment]
This is a pretty generic problem. That is, there could be any number of daemons making use of localized timestamps. IMHO this isn't a situation that should be solved in this module, but rather each sysadmin will need to understand what on their system might be affected by timezone changes and act accordingly.

**Comment by siebrand** [comment]
This is directly related to https://github.com/rsyslog/rsyslog/issues/424. One opinion there is "I do think whatever changes the timezone should also signal a reload/restart to the logging service"

**Comment by siebrand** [comment]
I'm closing this issue, because this module actually provides a solution for this using the parameter notify_services.

**Comment by siebrand** [comment]
Re-opened... So I've struggled with this issue on and off, and I think I gave it two good tries now.

The below config just won't work. What would be the correct configuration to have service rsyslog notified when timezone changes?

In a manifest:

`  ensure_resource('service', ['rsyslog'], { 'ensure' => 'running', 'enable' => 'true' })`

In hiera:

```
timezone::timezone: 'Europe/Helsinki'
timezone::notify_services:
  - rsyslog # This was try #1. Error: No title provided and "rsyslog" is not a valid resource reference
  - Service['rsyslog'] # Try #2. Error: Could not find resource 'Service['rsyslog']' in parameter 'notify'

```

**Comment by saz** [comment]
The second try is the right way, but it might be possible, that `Service['rsyslog']` comes later in the catalog?

**Comment by saz** [comment]
@siebrand Where you able to resolve this issue?

**Comment by siebrand** [comment]
Thanks for checking. It's deep down in my queue. Still to do. If you're certain it works, please feel free to close this ticket.

**Comment by saz** [comment]
As `timezone::notify_services` is working as expected for me, I'm closing this issue

**Comment by saz** [comment]
Whoops... Not working as expected.

**Comment by saz** [comment]
With the next release, you should be able to use notify_services like this:
```
timezone::notify_services:
  - 'rsyslog'
```
