### ISSUE TITLE
Module is causing systemd timedate service to restart on every run. 

### ISSUE THREAD

**Issue by nick-george** [saz/puppet-timezone#88]
Hi Saz, 

I have been investigating intermittent dropped SSL connection issues on RHEL7  systems. In doing so, I noticed the following logs for every single puppet run. I have narrowed the issue down to this module (no longer happens if I remove the module). I've looked through your code and for the life of me, I can't figure out why the service is getting restarted (your set-timezone exec looks good to me). Running puppet in trace & debug says that puppet wouldn't do the action to set the timezone. 

The dropped SSL connection issue happened at exactly the same time puppet ran. I'm wondering if restarting the time & date service has modified the system clock and caused the SSL library to drop connection(s).

```
Jul 18 05:10:43 host-01 dbus[2530]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
Jul 18 05:10:43 host-01 systemd: Starting Time & Date Service...
Jul 18 05:10:43 host-01 dbus[2530]: [system] Successfully activated service 'org.freedesktop.timedate1'
```

Thanks for your time. 
Nick

**Comment by mty22** [comment]
Just touching to confirm the same issue.

```
Jul 31 13:46:06 billing-dev puppet-agent[7947]: Applying configuration version '1564544755'
Jul 31 13:46:21 billing-dev dbus[3101]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
Jul 31 13:46:21 billing-dev systemd: Starting Time & Date Service...
Jul 31 13:46:21 billing-dev dbus[3101]: [system] Successfully activated service 'org.freedesktop.timedate1'
Jul 31 13:46:21 billing-dev systemd: Started Time & Date Service.
```

**Comment by saz** [comment]
@nick-george I know it's a long time since you've opened the issue, but have you found a solution for that?

**Comment by nick-george** [comment]
Hi @saz. I ended up determining that the dropped SSL connections were unrelated to the restart of the Time & Date service. I can't remember if I ended up fixing the restart issue though (was happening on a customer site). I'll take a look next time I'm there.

**Comment by saz** [comment]
As this is laying around for some longer time, I guess it's not relevant anymore. Feel free to let me know, if it's still relevant.
