### ISSUE TITLE
Puppet 6 support

### ISSUE THREAD

**Issue by voiprodrigo** [saz/puppet-timezone#92]
Hi,

Dont't know if it needs other changes other than metadata.

 Thanks.

**Comment by slconley** [comment]
I would like to see this too.  I can see that the stdlib dependency has been updated, but the module version was not bumped and forge doesn't have the update yet.

**Comment by saz** [comment]
I'll make a new release in a few minutes.

**Comment by Exidex** [comment]
It looks like you made the release but forgot to change puppet version range

**Comment by saz** [comment]
@Exidex You're absolutely right, sorry for that. v5.2.1 will be published shortly and fixes this issue
